/**
 * Visuals for procedurally generated quiz questions.
 *
 * Every activity, place, time of day, situation, slider end, "bothers" item,
 * superpower and companion has an icon or a sky tone, so each generated
 * question gets its own small illustrated "postcard" (see
 * src/ui/question-art.tsx). Tests check every bank item has one.
 */
import type { Category, Pole, Text } from "./content";

export type Tone = "dawn" | "morning" | "afternoon" | "evening" | "night" | "rain";

export const ACTIVITY_ICONS: Record<string, string> = {
  // energy +
  "squeezing through a packed night market": "🏮",
  "a big table where everyone talks at once": "🍻",
  "a rooftop party with a DJ": "🎧",
  "a festival with live music and crowds": "🎪",
  "a team game with lots of cheering": "📣",
  "meeting ten new people in one evening": "🤝",
  "a street-food crawl with eight new faces": "🍢",
  "a karaoke room with the whole group": "🎤",
  "a block party on a walking street": "🎊",
  "a pub quiz with a team of strangers": "🧠",
  "a countdown in a crowd by the river": "🎆",
  "a dance floor that fills up fast": "🪩",
  "a mookata dinner for twelve": "🥓",
  "a concert in a packed stadium": "🏟️",
  // energy −
  "a quiet corner in a small café": "☕",
  "a slow chat with two or three people": "💬",
  "a calm bench by the river": "🌊",
  "a small book or craft circle": "🧶",
  "a peaceful picnic in the park": "🧺",
  "a low-key board game table": "🎲",
  "a slow walk with one good friend": "🚶",
  "a tea tasting for four": "🍵",
  "a quiet dinner at a friend's place": "🕯️",
  "a boat ride with one friend": "⛵",
  "a reading afternoon in a library café": "📖",
  "a cooking night for three at home": "🍳",
  "a listening bar with good speakers and low voices": "📻",
  "a sunset on a quiet pier": "🌇",
  // explore +
  "a soi you've never walked down": "🛣️",
  "a dish you can't pronounce yet": "🥘",
  "a hidden spot someone just told you about": "🗝️",
  "a pop-up you saw online this morning": "📱",
  "a district across the river you rarely visit": "⛴️",
  "a class in something you've never tried": "🎓",
  "a ferry stop you've never got off at": "🚤",
  "a market in a district you've never visited": "🧭",
  "a cuisine you've never tasted": "🌮",
  "a night market that opened last month": "🆕",
  "a canal route you've only seen on a map": "📌",
  "a workshop by a maker you just discovered": "🔨",
  "the last stop on a train line": "🚉",
  "a fruit you've never seen at the market": "🥭",
  // explore −
  "your go-to noodle shop": "🍜",
  "a café that already knows your order": "🧋",
  "a park where you know every path": "🌳",
  "a favourite market you could walk blindfolded": "🛍️",
  "your usual running route, with company": "👟",
  "a restaurant you'd recommend to anyone": "⭐",
  "the café where you always sit by the window": "🪟",
  "the street-food stall you've loved for years": "🍡",
  "the khao man gai stall you'd queue for any day": "🍗",
  "a Sunday ritual you never skip": "🔁",
  "the bookshop where you know every shelf": "📗",
  "a walk around your own neighbourhood": "🏡",
  "the massage place you've trusted for years": "💆",
  "a dessert shop you've loved since school": "🍧",
  // rhythm +
  "a 10 pm street-food crawl": "🌃",
  "a late-night jazz bar": "🎷",
  "a midnight bike ride through the old town": "🚲",
  "a night market after 9 pm": "🌙",
  "a late movie and dessert after": "🍿",
  "a rooftop that stays open past midnight": "🌆",
  "a late-night khao tom run": "🍲",
  "a 1 am bowl of boat noodles": "🕐",
  "a night run when the city cools down": "🌠",
  "a gig that starts at 11 pm": "🎙️",
  "a midnight dessert run in Yaowarat": "🍨",
  "a night boat along the river": "🛥️",
  "a board game night that runs past 1 am": "♟️",
  "a 24-hour café after a late show": "🦉",
  // rhythm −
  "a 6 am run in the park": "🏃",
  "a morning market before the heat": "🥬",
  "sunrise by the river": "🌅",
  "breakfast jok at 7 am": "🥣",
  "a weekend morning yoga session": "🧘",
  "coffee on a quiet pier at dawn": "🌄",
  "a sunrise bike ride by the river": "🚴",
  "a dawn walk in Lumphini with the tai chi groups": "🌤️",
  "patongko and soy milk at 6:30": "🥛",
  "a flower market visit before sunrise": "💐",
  "an early swim before work": "🏊",
  "a breakfast meet-up at 8 am": "🥐",
  "a morning birdwatching walk": "🐦",
  "an early boat before the river gets busy": "🚣",
  // motion +
  "a walking food quest": "🗺️",
  "a bike tour": "🚲",
  "kayaking along a khlong": "🛶",
  "a pickup badminton or football game": "🏸",
  "a hands-on cooking class": "👩‍🍳",
  "a dance class": "💃",
  "a Muay Thai taster class": "🥊",
  "a volunteer park clean-up": "🧤",
  "a rock-climbing gym session": "🧗",
  "a sunset run along the river": "🏃‍♀️",
  "a frisbee game in the park": "🥏",
  "a long walk across three districts": "🥾",
  "a pottery wheel class": "🏺",
  "a takraw circle in the park": "🏐",
  // motion −
  "a long lunch where nobody rushes": "🍽️",
  "a gallery you take really slowly": "🖼️",
  "a rooftop seat watching the city": "🏙️",
  "a tasting table": "🥢",
  "a film screening": "🎬",
  "a long talk over Thai tea": "🧡",
  "a picnic with nothing to do but talk": "🧺",
  "an afternoon tea that runs long": "🫖",
  "a long brunch with endless refills": "🥞",
  "a cooking demo you just watch and taste": "👨‍🍳",
  "a slow boat with a good view": "🚢",
  "a coffee cupping": "☕",
  "a reading hour in a garden café": "🌺",
  "a dinner of four courses and three hours": "🍷",
  // plan +
  "deciding where to eat when you get hungry": "🤤",
  "following whatever looks interesting": "👀",
  "saying yes to a last-minute invite": "📲",
  "picking a random BTS stop and exploring": "🚝",
  "no itinerary, just vibes": "🎲",
  "hopping on the first boat that comes": "⛴️",
  "letting the group pick on the spot": "🙌",
  "following the smell of grilled pork down a soi": "🍖",
  "a day trip decided over breakfast": "🚐",
  "joining whatever's happening at the park": "🎈",
  "turning a quick coffee into a whole afternoon": "⏳",
  "letting a friend surprise you": "🎁",
  "taking the long way home on purpose": "🌀",
  "walking into a show without checking the lineup": "🎫",
  // plan −
  "booking the table a week ahead": "📅",
  "a route planned stop by stop": "📍",
  "checking opening hours and reviews first": "🔎",
  "a calendar invite with the whole plan": "🗓️",
  "knowing exactly how you're getting home": "🏠",
  "a shared list of three places to try": "📝",
  "tickets booked before anyone asks": "🎟️",
  "a packing list for a day out": "🎒",
  "a group chat poll to pick the date": "📊",
  "a Sunday spent getting the week ready": "🗂️",
  "a timed route that beats the traffic": "⏱️",
  "a reservation at the place everyone wants": "🔖",
  "a weather check and a plan B": "🌦️",
  "a meeting point and a time everyone agreed on": "🤙",
  // culture +
  "a contemporary art gallery": "🎨",
  "a design and makers market": "🛠️",
  "an indie café with a great playlist": "🎶",
  "a street-art walk": "🖌️",
  "a live indie gig": "🎸",
  "a Bangkok Design Week installation": "💡",
  "a new indie bookshop": "📚",
  "an artist talk in a converted warehouse": "🏭",
  "a zine fair": "📰",
  "an indie film night": "📽️",
  "a vintage and thrift market": "👗",
  "a photo walk at golden hour": "📸",
  "a pop-up dinner by a young chef": "🧑‍🍳",
  "a light art festival": "🌈",
  // culture −
  "an old-town temple walk": "🛕",
  "a heritage shophouse street": "🏘️",
  "a traditional market": "🧺",
  "a Thai craft workshop": "🪡",
  "a historic canal community": "🛶",
  "a Thai classical music performance": "🎻",
  "a shadow puppet show": "🎭",
  "a walk through a century-old market": "🏮",
  "a benjarong painting class": "🎏",
  "a khon masked dance performance": "👺",
  "an old-recipe Thai dessert shop": "🍮",
  "a wooden house museum by the canal": "🛖",
  "a garland-making workshop": "🌼",
  "a likay show at a neighbourhood fair": "🪭",
};

export const PLACE_ICONS: Record<string, string> = {
  Yaowarat: "🏮",
  "Talat Phlu": "🥟",
  "Khlong Bang Luang": "🛶",
  "Charoenkrung and Talat Noi": "🎨",
  "Little India (Phahurat)": "🧵",
  "Rattanakosin Island": "🛕",
  "Charoen Nakhon Road": "🌉",
  Asiatique: "🎡",
  "Lumphini Park": "🌳",
  "Benjakitti Forest Park": "🌿",
  Ari: "☕",
  Chatuchak: "🛍️",
  Siam: "🏙️",
  "Wat Arun riverside": "🛕",
  "Bang Krachao": "🚲",
  "Thonburi canals": "🛶",
  "Sanam Luang": "🪁",
  "Phra Athit Road": "🌊",
  "Ratchada night market": "🌙",
  "Song Wat Road": "🏘️",
  "Nang Loeng Market": "🍮",
  "Taling Chan Floating Market": "🚣",
  "Khlong Lat Mayom": "🥥",
  "Bangkok Art and Culture Centre": "🖼️",
  "Thong Lo": "🍸",
  Ekkamai: "🎶",
  Banglamphu: "🍜",
  "Khao San Road": "🎒",
  "Pak Khlong Talat flower market": "💐",
  "Santichaiprakan Park": "🌅",
  "Rot Fai Park": "🚴",
  "Wang Lang Market": "🍢",
  "Hua Takhe Old Market": "🛖",
  "Min Buri Old Market": "🧺",
  "Suan Luang Rama IX": "🌷",
  "Bang Khun Thian seaside": "🦀",
  "Huai Khwang night market": "🍤",
  "The Jam Factory": "📚",
  "Sam Yan": "🍲",
};

export const WHEN_TONES: Record<string, Tone> = {
  "Saturday morning": "morning",
  "After work on Thursday": "evening",
  "Sunday afternoon": "afternoon",
  "A rainy Friday evening": "rain",
  "A long weekend": "afternoon",
  "A cool December evening": "evening",
  "A hot April afternoon": "afternoon",
  "Late on a Saturday night": "night",
  "Sunday morning": "morning",
  "A Wednesday after a long day": "evening",
  "A free Friday night": "night",
  "Lunch break on a weekday": "afternoon",
  "A breezy evening after the rain": "evening",
  "The first morning of a long weekend": "dawn",
  "Songkran afternoon": "afternoon",
};

/** Sky and icon for each everyday situation. */
export const SITUATION_ART: Record<string, { tone: Tone; icon: string }> = {
  "A free Sunday with nothing booked": { tone: "afternoon", icon: "🗓️" },
  "A friend is visiting Bangkok for the weekend": { tone: "afternoon", icon: "🧳" },
  "It's raining hard on a Friday evening": { tone: "rain", icon: "☔" },
  "You just moved to a new neighbourhood": { tone: "morning", icon: "📦" },
  "It's the end of a long week": { tone: "evening", icon: "🛋️" },
  "It's a festival night in the city": { tone: "night", icon: "🎆" },
  "Your birthday falls on a Saturday": { tone: "evening", icon: "🎂" },
  "It's a cool morning in December": { tone: "dawn", icon: "🧣" },
  "A three-day weekend just started": { tone: "afternoon", icon: "🏖️" },
  "You have one free evening this week": { tone: "evening", icon: "⏳" },
  "A new friend asks you to plan the day": { tone: "afternoon", icon: "🤝" },
  "It's the first sunny day after a week of rain": { tone: "morning", icon: "🌤️" },
  "Your small group from Jurrgun wants to meet again": { tone: "evening", icon: "👋" },
  "Your cousin from Chiang Mai is in town for a day": { tone: "morning", icon: "🚆" },
  "It's a hot April afternoon with nowhere to be": { tone: "afternoon", icon: "🥵" },
  "You just finished a big project": { tone: "evening", icon: "🎉" },
  "You have a day off in the middle of the week": { tone: "morning", icon: "☀️" },
  "It's a breezy evening by the river": { tone: "evening", icon: "🌬️" },
  "It's Songkran week and the city slows down": { tone: "afternoon", icon: "💦" },
};

export const COMPANION_ICONS: Record<string, string> = {
  "a new friend from a Jurrgun event": "👋",
  "a friend visiting from another province": "🧳",
  "a colleague who just moved to Bangkok": "📦",
  "your small group from last week": "👥",
  "a cousin visiting from Chiang Mai": "🚆",
  "a classmate you haven't seen in years": "🎒",
  "a neighbour who just moved in": "🏡",
  "a friend from your running club": "👟",
  "a friend who never goes anywhere without a camera": "📷",
  "your language-exchange partner": "🗣️",
  "a friend who reads more than anyone you know": "📚",
  "a friend who will eat anything once": "😋",
  "a friend who always has a great playlist": "🎧",
  "your board game buddy": "🎲",
  "a friend who sketches everywhere they go": "✏️",
  "a friend and their very friendly dog": "🐕",
  "a fellow volunteer from a park clean-up": "🧤",
  "a café-hopping friend": "☕",
};

export const SLIDER_ICONS: Record<string, string> = {
  "A table of twenty": "👯",
  "The liveliest room in the soi": "🔊",
  "New people all night": "🫶",
  "A packed night market": "🏮",
  "A crowd singing along": "🎤",
  "Everyone you know, all at once": "🎉",
  "A table of three": "☕",
  "A quiet corner": "🪴",
  "One long conversation": "💬",
  "A calm park bench": "🌳",
  "A small circle of old friends": "🫂",
  "A café where you can hear the rain": "🌧️",
  "Somewhere I've never been": "🧭",
  "A menu I can't read yet": "📜",
  "A new soi every time": "🛣️",
  "The opening everyone's talking about": "🆕",
  "A ferry stop I've never tried": "🚤",
  "A dish I can't name": "🥘",
  "My usual spot": "🪑",
  "The order I always get": "🧋",
  "The soi I know by heart": "🏘️",
  "A place that knows my name": "👋",
  "My favourite stall": "🍡",
  "The same table as last time": "🔁",
  "Out until 2 am": "🌙",
  "Dinner at 10 pm": "🍽️",
  "The city after midnight": "🌃",
  "A late movie": "🍿",
  "Night markets and neon": "🏮",
  "Sleeping in on Sunday": "😴",
  "Up with the sunrise": "🌅",
  "Breakfast at 7": "🥣",
  "The city before 9 am": "🏙️",
  "A dawn run": "🏃",
  "Morning markets and mist": "🥬",
  "Home by 10 pm": "🏠",
  "On my feet all day": "👟",
  "A bike and a map": "🚲",
  "Learning a new move": "💃",
  "Ten kilometres of walking": "🥾",
  "A game of pickup football": "⚽",
  "Paddling a canal": "🛶",
  "A good seat all afternoon": "🛋️",
  "A long lunch": "🍽️",
  "One café, three hours": "☕",
  "A slow gallery": "🖼️",
  "Watching the river go by": "🌊",
  "A table full of small plates": "🥢",
  "Decide on the day": "🎲",
  "Follow whatever looks good": "👀",
  "A message saying come now": "📲",
  "No plan at all": "🍃",
  "See where the boat goes": "⛴️",
  "Pick a stop at random": "🚝",
  "Booked a week ahead": "📅",
  "A plan for every stop": "📍",
  "Reviews read in advance": "🔎",
  "A shared itinerary": "🗓️",
  "Tickets in hand": "🎟️",
  "A backup plan too": "🌦️",
  "A new gallery opening": "🎨",
  "A design market": "🛠️",
  "An indie gig": "🎸",
  "Street art and zines": "🖌️",
  "A pop-up studio": "💡",
  "A fresh light installation": "🌈",
  "An old shophouse street": "🏘️",
  "A century-old market": "🏮",
  "Thai classical music": "🎻",
  "A canal community": "🛶",
  "A heritage walk": "🗺️",
  "A traditional craft workshop": "🪡",
};

export const BOTHER_ICONS: Record<string, string> = {
  "A party that winds down at 9 pm": "🥱",
  "A dinner where only two people show up": "🪑",
  "A festival with hardly anyone there": "🏜️",
  "A quiet table when you're in the mood to chat": "🤐",
  "A group chat nobody replies to": "📵",
  "A table so loud you can't hear your friend": "🔊",
  "Being the only quiet one at a big party": "🫥",
  "A night with no moment to talk properly": "💭",
  "A plus-one who brings ten more people": "📢",
  "A packed market when you wanted a slow stroll": "🚶",
  "Ending up at the same place every weekend": "🔁",
  "Ordering the same dish again": "🍽️",
  "A trip where you only see what you've seen before": "🙈",
  "Never trying the soi next door": "🚧",
  "A favourite spot that never adds anything new": "😐",
  "Your favourite café changing its whole menu": "📋",
  "A new place that turns out to be a miss": "🎯",
  "Your go-to stall moving across town": "🚚",
  "Trying three new places and loving none": "🤷",
  "Getting lost on the way somewhere new": "🧭",
  "A dinner that ends just as you're warming up": "🦉",
  "A 7 am meet-up": "⏰",
  "Leaving a great night early": "🚪",
  "A weekend with nothing open after dark": "🌑",
  "An alarm on a Sunday": "🔔",
  "Dinner plans that start at 10 pm": "🕙",
  "Missing the cool morning air": "🍃",
  "Sleeping through a whole weekend morning": "🛌",
  "A night out that goes past 1 am": "🌙",
  "Reaching the morning market as it packs up": "🧺",
  "Sitting in one café all afternoon": "🪑",
  "A day out with no walking at all": "🚕",
  "Watching a game you'd rather be playing": "👀",
  "A class where you only take notes": "📝",
  "A rainy day stuck indoors": "🌧️",
  "Rushing through a great meal": "⏩",
  "A tour that never stops long enough to sit": "🏃",
  "Being too out of breath to talk": "😮‍💨",
  "A gallery you have to see in ten minutes": "⌛",
  "Skipping dessert to catch the next stop": "🍮",
  "A day planned to the minute": "⏱️",
  "Booking a table three weeks ahead": "📆",
  "Saying no to a fun last-minute invite": "🙅",
  "A long group chat to pick one restaurant": "💬",
  "Skipping a great detour because it isn't on the plan": "🚫",
  "Arriving to find the place fully booked": "🈵",
  "Nobody knowing where we're going next": "❓",
  "A plan that changes three times in one day": "🔀",
  "Finding out the market closed an hour ago": "🕐",
  "Not knowing how you'll get home": "🏠",
  "Missing the opening night of a new show": "🎨",
  "A weekend with nothing new to see": "🫤",
  "Hearing about a great pop-up after it closed": "📭",
  "A playlist of only old hits": "📻",
  "Seeing the same museum display again": "🏛️",
  "A food tour that skips the old family recipes": "🍲",
  "Missing the last show of a folk performance": "🎭",
  "A trip with no time for the old town": "🏘️",
  "Never hearing the story behind a place": "📖",
  "A craft fair with nothing handmade": "🧵",
};

export const POWER_ICONS: Record<string, string> = {
  "Remember every name at a party of thirty": "🧠",
  "Turn any table into the fun table": "🎉",
  "Always know where tonight's crowd is": "📡",
  "Find a quiet table anywhere, even Siam on a Saturday": "🤫",
  "Make any café feel like your living room": "🛋️",
  "Turn small talk into a real conversation": "💬",
  "Hear about every new opening a week early": "🔭",
  "Read any menu in any language": "🈶",
  "Never get lost, however deep the soi": "🧭",
  "Your favourite stalls never close or move": "🏪",
  "Always get your usual table": "🪑",
  "Your go-to dish tastes perfect every time": "🍜",
  "Night markets that stay open until 3 am": "🌙",
  "Never feel tired the morning after": "🦉",
  "A ride home that's always waiting": "🚕",
  "A cool 22 degree morning every day": "🌤️",
  "Wake up fresh without an alarm": "🌅",
  "First in line at every morning market": "🥇",
  "Never feel the heat on a long walk": "🧊",
  "Pick up any sport in one afternoon": "🏸",
  "Legs that never get tired": "🦵",
  "Always get the seat with the best view": "🏙️",
  "A meal that's never rushed": "🍽️",
  "Bottomless Thai tea, always the right sweetness": "🧋",
  "Every last-minute plan works out": "✨",
  "Always reach the pier just as the boat arrives": "⛴️",
  "Find something fun wherever you get off": "🎈",
  "Every booking works first try": "✅",
  "Know the queue time before you leave home": "⏲️",
  "A plan that everyone actually follows": "🗺️",
  "A front-row pass to every opening and gig": "🎫",
  "Meet the artist at every exhibition": "🎨",
  "Spot the next creative neighbourhood first": "🔮",
  "A local storyteller in every old neighbourhood": "📜",
  "Master any Thai craft in a day": "🪡",
  "Hear what an old street sounded like 100 years ago": "🕰️",
};

/** One icon per pole, for templates without a place (quick, skip, scale). */
export const POLE_ICONS: Record<Category, { plus: string; minus: string; tone: Tone }> = {
  energy: { plus: "🎉", minus: "🍵", tone: "evening" },
  explore: { plus: "🧭", minus: "🏠", tone: "afternoon" },
  rhythm: { plus: "🌙", minus: "🌅", tone: "dawn" },
  motion: { plus: "🚲", minus: "🍜", tone: "morning" },
  plan: { plus: "🎲", minus: "🗓️", tone: "afternoon" },
  culture: { plus: "🎨", minus: "🛕", tone: "evening" },
};

function poleIcon(category: Category, pole: Pole): string {
  return pole === 1 ? POLE_ICONS[category].plus : POLE_ICONS[category].minus;
}

export function activityIcon(a: Text, category: Category, pole: Pole): string {
  return ACTIVITY_ICONS[a.en] ?? poleIcon(category, pole);
}

/** Icon for any bank phrase (slider end, bothers item, superpower), with a pole fallback. */
export function phraseIcon(a: Text, category: Category, pole: Pole): string {
  return SLIDER_ICONS[a.en] ?? BOTHER_ICONS[a.en] ?? POWER_ICONS[a.en] ?? ACTIVITY_ICONS[a.en] ?? poleIcon(category, pole);
}

/** What the picture above a question shows. Built server-side, rendered by question-art.tsx. */
export type Art = {
  tone: Tone;
  /** Big icon(s) in the scene: the place, or the two options. */
  icons: string[];
  /** Short caption on the postcard, e.g. the place name. */
  caption?: Text;
  /** Seeds the skyline so each question looks a little different. */
  seed: number;
};
