/**
 * Bundles the browser half of the `sv-map` package (node_modules/sv-map) into
 * src/vendor/sv-map.generated.ts, so the Worker can serve it at /vendor/…
 * (Workers have no filesystem at runtime). Re-run after updating the package:
 *
 *   npm run svmap
 */
import { readFileSync, writeFileSync } from "node:fs";

const read = (p) => readFileSync(new URL(`../node_modules/sv-map/${p}`, import.meta.url), "utf8");
const pkg = JSON.parse(read("package.json"));
// Stored base64-encoded: the deploy pipeline scans the built bundle for
// `from "./…"` to find extra modules, and sv-map's docs contain exactly that.
const b64 = (s) => Buffer.from(s, "utf8").toString("base64");
const out = `// GENERATED by scripts/build-svmap.mjs from the sv-map package — do not edit.
// Base64 so the package's source text never appears in the built bundle.
export const SV_MAP_VERSION = ${JSON.stringify(pkg.version)};
export const SV_MAP_JS_B64 = ${JSON.stringify(b64(read("src/sv-map.js")))};
export const SV_MAP_CSS_B64 = ${JSON.stringify(b64(read("src/sv-map.css")))};
`;
writeFileSync(new URL("../src/vendor/sv-map.generated.ts", import.meta.url), out);
console.log(`wrote src/vendor/sv-map.generated.ts (sv-map ${pkg.version})`);
