// GENERATED by `npm run assets` — do not edit by hand.
//
// One entry per file in design/assets/. Import `asset` rather than writing the
// URL as a string: the type is built from this list, so a typo is a typecheck
// error on your machine instead of a broken image in your demo.
//
//   import { asset } from "./assets";
//   `<img src="${asset("logo.svg")}" alt="Our logo" />`
//
// Add a file to design/assets/, run `npm run assets`, and commit both.

export const assets = {} as const;

/** Every asset path available to this app, e.g. `"logo.svg"` or `"icons/cart.svg"`. */
export type AssetPath = keyof typeof assets;

/** The URL your app serves `path` from. See the `/assets/*` route in index.ts. */
export function asset(path: AssetPath): string {
  return assets[path];
}
