// GENERATED by scripts/build-migrations.mjs from drizzle/*.sql — do not edit.
export const MIGRATIONS: { id: string; statements: string[] }[] = [
  {
    "id": "0000_happy_azazel",
    "statements": [
      "CREATE TABLE \"identity_accounts\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"username\" text NOT NULL,\n\t\"password_hash\" text NOT NULL,\n\t\"password_salt\" text NOT NULL,\n\t\"role\" text DEFAULT 'user' NOT NULL,\n\t\"partner_org_id\" text,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"suspended_until\" timestamp with time zone,\n\t\"deactivated_at\" timestamp with time zone,\n\t\"verification\" text DEFAULT 'none' NOT NULL,\n\t\"bkk_registered\" text DEFAULT 'not_checked' NOT NULL,\n\t\"research_id\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"identity_audit_log\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"actor\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"target_type\" text,\n\t\"target_id\" text,\n\t\"detail\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_blocks\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"blocker\" text NOT NULL,\n\t\"blocked\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_buddy_pairs\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"members\" jsonb NOT NULL,\n\t\"method\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_connection_choices\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"from_account\" text NOT NULL,\n\t\"to_account\" text NOT NULL,\n\t\"choice\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_connections\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"a_account\" text NOT NULL,\n\t\"b_account\" text NOT NULL,\n\t\"level\" text NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"removed_at\" timestamp with time zone\n);",
      "CREATE TABLE \"social_consents\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"category\" text NOT NULL,\n\t\"granted\" boolean NOT NULL,\n\t\"version\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_contact_shares\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"connection_id\" text NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"method\" text NOT NULL,\n\t\"value\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_events\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"title_en\" text,\n\t\"description\" text DEFAULT '' NOT NULL,\n\t\"description_en\" text,\n\t\"cover_key\" text,\n\t\"starts_at\" timestamp with time zone NOT NULL,\n\t\"ends_at\" timestamp with time zone NOT NULL,\n\t\"venue_name\" text NOT NULL,\n\t\"venue_address\" text DEFAULT '' NOT NULL,\n\t\"map_url\" text,\n\t\"district\" text NOT NULL,\n\t\"capacity\" integer NOT NULL,\n\t\"age_min\" integer DEFAULT 18 NOT NULL,\n\t\"age_max\" integer DEFAULT 99 NOT NULL,\n\t\"languages\" jsonb DEFAULT '[\"th\"]'::jsonb NOT NULL,\n\t\"cost_thb\" integer DEFAULT 0 NOT NULL,\n\t\"payment_note\" text,\n\t\"host_account_id\" text,\n\t\"partner_org_id\" text,\n\t\"intensity\" text DEFAULT 'social' NOT NULL,\n\t\"group_min\" integer DEFAULT 4 NOT NULL,\n\t\"group_max\" integer DEFAULT 6 NOT NULL,\n\t\"plus_one_allowed\" boolean DEFAULT false NOT NULL,\n\t\"accessibility\" text DEFAULT '' NOT NULL,\n\t\"safety_info\" text DEFAULT '' NOT NULL,\n\t\"emergency_contact\" text DEFAULT '' NOT NULL,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"status\" text DEFAULT 'draft' NOT NULL,\n\t\"resident_priority\" boolean DEFAULT false NOT NULL,\n\t\"resident_quota\" integer DEFAULT 0 NOT NULL,\n\t\"buddy_enabled\" boolean DEFAULT false NOT NULL,\n\t\"buddy_round_at\" timestamp with time zone,\n\t\"groups_published_at\" timestamp with time zone,\n\t\"active_prompt\" text,\n\t\"visitbangkok_route\" text,\n\t\"created_by\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_feedback\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"met_new_person\" boolean,\n\t\"would_meet_again\" boolean,\n\t\"felt_safe\" integer,\n\t\"group_rating\" integer,\n\t\"comment\" text DEFAULT '' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_moderation_actions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"report_id\" text,\n\t\"account_id\" text NOT NULL,\n\t\"action\" text NOT NULL,\n\t\"until\" timestamp with time zone,\n\t\"note\" text DEFAULT '' NOT NULL,\n\t\"by\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_notifications\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"title_th\" text NOT NULL,\n\t\"title_en\" text NOT NULL,\n\t\"link\" text,\n\t\"read_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"identity_partner_orgs\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_profiles\" (\n\t\"account_id\" text PRIMARY KEY NOT NULL,\n\t\"nickname\" text NOT NULL,\n\t\"birth_date\" date NOT NULL,\n\t\"district\" text NOT NULL,\n\t\"languages\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"interests\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"social_styles\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"event_style\" text,\n\t\"intents\" jsonb DEFAULT '[\"friends\"]'::jsonb NOT NULL,\n\t\"relationship\" text DEFAULT 'prefer_not' NOT NULL,\n\t\"last_single_switch_at\" timestamp with time zone,\n\t\"romance_on\" boolean DEFAULT false NOT NULL,\n\t\"gender_identity\" text,\n\t\"romance_open_to\" jsonb,\n\t\"pronouns\" text,\n\t\"show_pronouns\" boolean DEFAULT false NOT NULL,\n\t\"age_min\" integer DEFAULT 18 NOT NULL,\n\t\"age_max\" integer DEFAULT 99 NOT NULL,\n\t\"prompts\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"photo_key\" text,\n\t\"newcomer\" boolean DEFAULT false NOT NULL,\n\t\"locale\" text DEFAULT 'th' NOT NULL,\n\t\"onboarded_at\" timestamp with time zone,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"research_pulse_questions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"prompt_th\" text NOT NULL,\n\t\"prompt_en\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"options\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"status\" text DEFAULT 'draft' NOT NULL,\n\t\"active_from\" timestamp with time zone,\n\t\"active_to\" timestamp with time zone,\n\t\"segment\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"sort_order\" integer DEFAULT 0 NOT NULL,\n\t\"created_by\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"research_pulse_responses\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"question_id\" text NOT NULL,\n\t\"research_id\" text NOT NULL,\n\t\"answer\" jsonb NOT NULL,\n\t\"district\" text,\n\t\"age_band\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_registrations\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"offered_until\" timestamp with time zone,\n\t\"plus_one_with\" text,\n\t\"plus_one_username\" text,\n\t\"wants_buddy\" boolean DEFAULT false NOT NULL,\n\t\"pass_token\" text NOT NULL,\n\t\"checked_in_at\" timestamp with time zone,\n\t\"checked_in_by\" text,\n\t\"check_in_method\" text,\n\t\"group_no\" integer,\n\t\"social_signal\" text,\n\t\"signal_topics\" jsonb,\n\t\"no_show_recorded\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"cancelled_at\" timestamp with time zone\n);",
      "CREATE TABLE \"social_reports\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"reporter\" text NOT NULL,\n\t\"target_account\" text,\n\t\"target_event\" text,\n\t\"reason\" text NOT NULL,\n\t\"details\" text DEFAULT '' NOT NULL,\n\t\"severity\" text DEFAULT 'standard' NOT NULL,\n\t\"status\" text DEFAULT 'open' NOT NULL,\n\t\"resolved_by\" text,\n\t\"resolved_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"identity_sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_strikes\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"account_id\" text NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"reason\" text NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"waived_by\" text,\n\t\"waived_reason\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"research_wellbeing\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"research_id\" text NOT NULL,\n\t\"phase\" text NOT NULL,\n\t\"q1\" integer NOT NULL,\n\t\"q2\" integer NOT NULL,\n\t\"q3\" integer NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE UNIQUE INDEX \"identity_accounts_username_idx\" ON \"identity_accounts\" (\"username\");",
      "CREATE INDEX \"identity_accounts_role_idx\" ON \"identity_accounts\" (\"role\");",
      "CREATE INDEX \"identity_audit_created_idx\" ON \"identity_audit_log\" (\"created_at\");",
      "CREATE INDEX \"identity_audit_actor_idx\" ON \"identity_audit_log\" (\"actor\");",
      "CREATE UNIQUE INDEX \"social_blocks_pair_idx\" ON \"social_blocks\" (\"blocker\",\"blocked\");",
      "CREATE INDEX \"social_blocks_blocked_idx\" ON \"social_blocks\" (\"blocked\");",
      "CREATE INDEX \"social_buddy_pairs_event_idx\" ON \"social_buddy_pairs\" (\"event_id\");",
      "CREATE UNIQUE INDEX \"social_choices_unique_idx\" ON \"social_connection_choices\" (\"event_id\",\"from_account\",\"to_account\");",
      "CREATE INDEX \"social_choices_to_idx\" ON \"social_connection_choices\" (\"event_id\",\"to_account\");",
      "CREATE UNIQUE INDEX \"social_connections_pair_event_idx\" ON \"social_connections\" (\"a_account\",\"b_account\",\"event_id\");",
      "CREATE INDEX \"social_connections_b_idx\" ON \"social_connections\" (\"b_account\");",
      "CREATE INDEX \"social_consents_account_idx\" ON \"social_consents\" (\"account_id\",\"category\");",
      "CREATE UNIQUE INDEX \"social_contact_shares_idx\" ON \"social_contact_shares\" (\"connection_id\",\"account_id\");",
      "CREATE INDEX \"social_events_starts_idx\" ON \"social_events\" (\"starts_at\");",
      "CREATE INDEX \"social_events_district_idx\" ON \"social_events\" (\"district\");",
      "CREATE INDEX \"social_events_status_idx\" ON \"social_events\" (\"status\");",
      "CREATE UNIQUE INDEX \"social_feedback_unique_idx\" ON \"social_feedback\" (\"event_id\",\"account_id\");",
      "CREATE INDEX \"social_moderation_account_idx\" ON \"social_moderation_actions\" (\"account_id\");",
      "CREATE INDEX \"social_moderation_report_idx\" ON \"social_moderation_actions\" (\"report_id\");",
      "CREATE INDEX \"social_notifications_account_idx\" ON \"social_notifications\" (\"account_id\",\"created_at\");",
      "CREATE INDEX \"social_profiles_district_idx\" ON \"social_profiles\" (\"district\");",
      "CREATE INDEX \"research_pulse_questions_status_idx\" ON \"research_pulse_questions\" (\"status\");",
      "CREATE UNIQUE INDEX \"research_pulse_responses_unique_idx\" ON \"research_pulse_responses\" (\"question_id\",\"research_id\");",
      "CREATE INDEX \"research_pulse_responses_q_idx\" ON \"research_pulse_responses\" (\"question_id\");",
      "CREATE UNIQUE INDEX \"social_registrations_event_account_idx\" ON \"social_registrations\" (\"event_id\",\"account_id\");",
      "CREATE UNIQUE INDEX \"social_registrations_pass_idx\" ON \"social_registrations\" (\"pass_token\");",
      "CREATE INDEX \"social_registrations_account_idx\" ON \"social_registrations\" (\"account_id\");",
      "CREATE INDEX \"social_registrations_event_status_idx\" ON \"social_registrations\" (\"event_id\",\"status\");",
      "CREATE INDEX \"social_reports_status_idx\" ON \"social_reports\" (\"status\",\"created_at\");",
      "CREATE INDEX \"social_reports_target_idx\" ON \"social_reports\" (\"target_account\");",
      "CREATE INDEX \"identity_sessions_account_idx\" ON \"identity_sessions\" (\"account_id\");",
      "CREATE INDEX \"social_strikes_account_idx\" ON \"social_strikes\" (\"account_id\");",
      "CREATE UNIQUE INDEX \"social_strikes_event_account_idx\" ON \"social_strikes\" (\"event_id\",\"account_id\");",
      "CREATE UNIQUE INDEX \"research_wellbeing_unique_idx\" ON \"research_wellbeing\" (\"research_id\",\"phase\");"
    ]
  },
  {
    "id": "0001_burly_deathstrike",
    "statements": [
      "CREATE TABLE \"social_invites\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"inviter\" text NOT NULL,\n\t\"used_by\" text,\n\t\"used_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"identity_login_attempts\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"username\" text NOT NULL,\n\t\"ip_hash\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"social_vibes\" (\n\t\"account_id\" text PRIMARY KEY NOT NULL,\n\t\"vector\" jsonb NOT NULL,\n\t\"archetype\" text NOT NULL,\n\t\"modifier\" text,\n\t\"seen\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"visible\" boolean DEFAULT false NOT NULL,\n\t\"taken_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"social_profiles\" ADD COLUMN \"show_resident_badge\" boolean DEFAULT false NOT NULL;",
      "CREATE INDEX \"social_invites_event_inviter_idx\" ON \"social_invites\" (\"event_id\",\"inviter\");",
      "CREATE INDEX \"identity_login_attempts_user_idx\" ON \"identity_login_attempts\" (\"username\",\"created_at\");",
      "CREATE INDEX \"identity_login_attempts_ip_idx\" ON \"identity_login_attempts\" (\"ip_hash\",\"created_at\");"
    ]
  },
  {
    "id": "0002_purple_black_panther",
    "statements": [
      "ALTER TABLE \"social_profiles\" ADD COLUMN \"bio\" jsonb DEFAULT '{}'::jsonb NOT NULL;"
    ]
  }
];
