#!/usr/bin/env bash
#
# Uploads whatever of design/assets/ this environment does not already have.
#
# Managed by SV Cloud. Both jobs in deploy.yml run it — the branch job before
# deploying, the tag job before promoting — because each environment has its own
# separate storage and a promotion moves code, not files.
#
# YOUR ASSETS ARE ADDRESSED BY THEIR CONTENT. src/assets.ts (generated by
# `npm run assets`) maps each file to /assets/<content hash>/<path>, so:
#
#   - uploading can never overwrite anything. Change a file and it gets a new
#     address; the old one stays where it is, still used by whatever version of
#     your app is running against it.
#   - a rollback works. Older code asks for the addresses it was built with,
#     and they still resolve.
#
# So this does not need to work out what a commit changed. It asks SV Cloud
# which of the addresses this build uses are missing, and sends only those —
# correct after a force push, and correct the first time a promotion brings a
# commit's assets to your live app.
#
# SV Cloud keeps the assets used by your last few deploys on each environment
# and removes the rest. If you go further back than that, push the old code and
# let it rebuild: this step puts the files back.
set -euo pipefail

if [ ! -d design/assets ]; then exit 0; fi

OIDC=$(curl -sSf -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
  "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$CLOUD_API_URL" | jq -r '.value')

# Every storage address this build's code refers to, straight out of the
# generated manifest, so the list can never disagree with what the app asks for.
KEYS=$(node -e '
const fs = require("fs");
const src = fs.readFileSync("src/assets.ts", "utf8");
const keys = new Set();
for (const m of src.matchAll(/"\/assets\/([^"\s]+)"/g)) keys.add("assets/" + m[1]);
process.stdout.write(JSON.stringify([...keys]));
')

if [ "$KEYS" = "[]" ] || [ -z "$KEYS" ]; then
  echo "No design assets referenced by this build."
  exit 0
fi

MISSING=$(curl -sSf -X POST -H "Authorization: Bearer $OIDC" \
  -H "content-type: application/json" \
  --data "{\"keys\":$KEYS}" \
  "$CLOUD_API_URL/api/v1/projects/deploy/assets/missing" | jq -r '.missing[]')

if [ -z "$MISSING" ]; then
  echo "Every design asset this build uses is already in place."
  exit 0
fi

# The storage address carries the content hash as its first segment; the file on
# disk is at the rest of it.
LIST=$(mktemp)
while IFS= read -r KEY; do
  [ -n "$KEY" ] || continue
  REL="${KEY#assets/}"
  PATH_IN_REPO="design/assets/${REL#*/}"
  [ -f "$PATH_IN_REPO" ] || { echo "::warning::$PATH_IN_REPO is referenced but not in this commit"; continue; }
  printf '%s\t%s\n' "$KEY" "$PATH_IN_REPO" >> "$LIST"
done <<< "$MISSING"

COUNT=$(wc -l < "$LIST" | tr -d ' ')
echo "$COUNT file(s) to upload."

# The checkout left LFS pointers, so fetch the real bytes for exactly this list.
# Guarded on git-lfs existing at all: a repo whose owner never installed it has
# ordinary files here, already checked out, and must not fail the build over a
# tool it does not use.
if command -v git-lfs > /dev/null 2>&1; then
  INCLUDE=""
  while IFS=$'\t' read -r _ FILE; do
    case "$FILE" in
      *,*) git lfs pull --include="$FILE" ;;
      *) INCLUDE="${INCLUDE:+$INCLUDE,}$FILE" ;;
    esac
  done < "$LIST"
  if [ -n "$INCLUDE" ]; then git lfs pull --include="$INCLUDE"; fi
fi

while IFS=$'\t' read -r KEY FILE; do
  REL="${KEY#assets/}"
  TYPE=$(file -b --mime-type "$FILE")
  # The size is signed INTO the upload URL, so it is a real ceiling rather than
  # something we merely claim. Sending any other number of bytes is refused by
  # storage before one is written.
  SIZE=$(wc -c < "$FILE" | tr -d ' ')
  echo "  uploading $REL ($SIZE bytes)"
  URL=$(curl -sSf -G -H "Authorization: Bearer $OIDC" \
    --data-urlencode "path=$REL" \
    --data-urlencode "content_length=$SIZE" \
    --data-urlencode "content_type=$TYPE" \
    "$CLOUD_API_URL/api/v1/projects/deploy/assets/upload-url" | jq -r '.url')
  curl -sSf -X PUT --upload-file "$FILE" -H "content-type: $TYPE" "$URL"
done < "$LIST"

rm -f "$LIST"
